local _
local AddonName, ns =...
local L = CreateFrame"Frame"
ns.L = L

if (GetLocale() == "zhCN") then 
	--默认语言为简体中文

elseif (GetLocale() == "ruRU") then 
	--by:ZamestoTV
	L.resd	= "Перезагрузите интерфейс, чтобы восстановить настройки по умолчанию"
	L.confirm	= "Подтвердить"
	L.cancel	= "Отмена"
	L.dtools2	= "Украшение интерфейса"
	L.captext	= "|cff00EE00Shift|r - удерживайте для перемещения стандартных аватаров, темных кровяных клеток, информации и т.д.\n(Настройка панели действий может отключить панель действий)\n|cff00EE00/di|r - Быстро открыть интерфейс настроек\n|cff00EE00/npd|r - Восстановить настройки индикаторов здоровья по умолчанию"
	L.printh2	= "|cff00EE00/rl|r - Перезагрузить интерфейс\n|cff00EE00/di|r - Быстро открыть интерфейс настроек"
	L.printh	= "Инструкции"

	L.acu1	= "Панель действий"
	L.acu2	= "Улучшение и украшение панели действий"
	L.acc1	= "Черная рамка"
	L.acc2	= "Окрасить рамку кнопок панели действий"
	L.acp1	= "Продвинутое украшение"
	L.acp2	= "Украсить фон рамки кнопок панели действий"
	L.acr1	= "Скрыть анимацию иконок"
	L.acr2	= "Отключить анимацию заклинаний для новых иконок в 10.0"
	L.unu1	= "Улучшение окон"
	L.unu2	= "Улучшение и украшение стандартных окон"
	L.unft1 = "Текстура Элиты"
	L.unft2 = "Окно игрока с текстурой золотого дракона"
	L.una1 	= "Исчезновение окна игрока"
	L.una2	= "Окно для постепенного исчезновения аватара без цели в бою"
	L.pnc1	= "Переименование персонажа"
	L.pnc2	= "|cff00FF00/gn/name|r - Изменить имя локального персонажа"
	L.unfn1 = "Скрыть имя"
	L.unfn2 = "Скрыть имя игрока"
	L.unc1	= "Настройка цвета класса"
	L.unc2	= "Использовать яркий набор цветов для классов"
	L.otb1	= "Украшение отслеживания"
	L.otb2	= "Украшение текста отслеживания заданий (Возможны сбои в поведении интерфейса во время боя)"
	L.sfu1	= "Украшение шрифтов"
	L.sfu2	= "Украшение большей части текста в игре"
	L.ruu1	= "Украшение окна рейда"
	L.ruu2	= "Украшение окон рейда"
	L.npu1	= "Улучшение индикаторов здоровья"
	L.npu2	= "Простое улучшение и украшение индикаторов здоровья"
	L.tiu1	= "Улучшение подсказок"
	L.tiu2	= "Украшение и улучшение подсказок при наведении мыши"

	L.aur1	= "Авторемонт"
	L.aur2	= "Автоматический ремонт снаряжения (приоритет у ремонта гильдии)"
	L.aus1	= "Автопродажа"
	L.aus2	= "Автоматическая продажа серого мусора"
	L.aua1	= "Автоскриншоты"
	L.aua2	= "Автоматическое создание скриншотов при получении достижений"
	L.aug1	= "Автоформирование"
	L.aug2	= "Автоматическое формирование шифротекста (|cffFFFF00/1|r)"
	L.fsl1	= "Быстрый сбор"
	L.fsl2	= "Ускорение окна сбора"
	L.ist1	= "Прерывание подсказок"
	L.ist2	= "Подсказка о прерывании заклинания цели"
	L.vap1	= "Голосовые объявления"
	L.vap2	= "Голосовая подсказка при получении метки"
	L.bfm1	= "Перемещение панелей"
	L.bfm2	= "Свободное перемещение встроенных панелей"
	L.ifs1	= "Информация о данных"
	L.ifs2	= "Скорость передвижения, FPS, Задержка, Память"
	L.ifsb1	= "Большой шрифт"
	L.ifsb2	= "Увеличение размера шрифта для информации о данных"
	L.cfp1	= "Улучшение чата"
	L.cfp2	= "Украшение и улучшение чата"
	L.cfbb1	= "Нижняя кнопка"
	L.cfbb2	= "Перемещение кнопки чата в нижнюю часть окна"
	L.cbi1	= "Индикатор боя"
	L.cbi2	= "Индикатор боя от Bigfoot"

	L.oufd1	= "Сфера Диабло"
	L.oufd2	= "Окно игрока Сферы Диабло от oUF"
	L.oufcc1= "Цвет класса"
	L.oufcc2= "Окрашивание сферы в цвет класса"
	L.dpet1	= "Окно питомца"
	L.dpet2	= "Окно питомца над сферой жизни"
	L.dduf1	= "Стандартное окно"
	L.dduf2	= "Включить стандартное окно игрока, скрытый oUF"
	L.uisl1	= "Блокировка масштаба интерфейса"
	L.uisl2	= "Открыть и заблокировать масштаб интерфейса (После настройки масштаба интерфейса необходимо сбросить позиции)"
	L.daml1	= "Тонкая настройка действий"
	L.daml2	= "Настройка и блокировка некоторых панелей действий (Режим редактирования может вызывать ошибки во время боя)"

	L.tipc1	= "Подсказка: Следовать"
	L.tipc2	= "Подсказка: Не следовать"
	L.tipc3	= "Подсказка: Следовать вне боя"
	L.sqw1	= "Задержка заклинания"
	L.sqw2	= "Задержка последовательности заклинаний"
	L.brtx	= "Версия"
	L.adrl	= "Перезагрузить"
	L.liver	= "Прямая трансляция"
	L.slb		= "Рекомендация"
	L.resdef	= "Восстановить по умолчанию"
	L.respos	= "Сбросить позицию"
	L.liveroom	= "|cffEEFF7FDouyuLive:|r427397"
	L.print	= "Открыть интерфейс настроек"

	-- Чат
	L.say		= "С"
	L.yell		= "К"
	L.party		= "Г"
	L.guild		= "Г"
	L.raid		= "Р"
	L.instance		= "П"
	L.general1		= "О"
	L.general2		= "Общий"
	L.general3		= "У вас нет общего канала"
	L.trade1		= "Т"
	L.trade2		= "Торговля"
	L.trade3		= "Вы не в торговом канале, присоединитесь в главном городе"
	L.lookingforgroup1		= "Л"
	L.lookingforgroup2		= "Поиск группы"
	L.lookingforgroup3		= "Присоединился к поиску группы"
	L.lookingforgroup4		= "Покинул поиск группы"
	L.world1		= "М"
	L.world2		= "Мир"
	L.world3		= "Присоединился к мировому каналу"
	L.world4		= "Покинул мировой канал"
	L.rep		= "Р"
	L.eql		= "Ур. экипировки"
	L.class		= "Класс"
	L.spec		= "Специализация"

	-- Информация
	L.fps 	= "FPS"
	L.lag 	= "Задержка"
	L.player 	= "И"
	L.target 	= "Ц"
	L.vehicle 	= "Т"
	L.none 	= "Нет"
	L.lootspec 	= "СПЕЦ"
	L.str 	= "Сил"
	L.agi 	= "Лов"
	L.int 	= "Инт"
	L.cri 	= "Крит"
	L.has 	= "Есть"
	L.mas 	= "Мастер"
	L.ver 	= "Вер"
	L.clearm	= "Очистить память"
	L.total		= "Всего"
	L.totalb	= "Всего, включая Blizzard"
	L.sspec		= "Сменить специализацию"
	L.nospec	= "Еще не специализирован"
	L.slspec	= "Сменить специализацию для сбора"

	-- Модули
	L.guildrepair	= "В этот раз использован ремонт гильдии"
	L.guildra		= "Осталось доступных ремонтов гильдии"
	L.selfrepair	= "Ремонт за свой счет"
	L.norepair		= "У меня нет денег на ремонт снаряжения."
	L.sellg			= "Продажа мусора"
	L.hidoroff		= "Сторона невидима или персонаж не в сети, невозможно пригласить"
	L.cutin 		= "Вырезать "
	L.enytc 		= "Введите имя, которое хотите изменить, оставьте пустым для восстановления оригинального имени"
	L.carti 		= "Подтвердите и перезагрузите интерфейс"

	-- Другое
	L.buyco		= "Успешно куплен 1 предмет"
	L.buydpc	= "Ошибка покупки, изменилась цена"
	L.buyalp	= "Купить по минимальной цене"
	L.untre		= "Невозможно сбросить"
	L.hbre		= "Сброшено"
	L.hbre		= "Сброшено"
	L.ltteam	= "Покидание команды"
	L.ftayt		= "Для этого мероприятия ваша команда заполнена и будет удалена из списка"
	L.era		= "ЭРА"

	-- Настройки аддона
	L.cdscr	= "Настройки DBM, Skada.. изменены, перезагрузка интерфейса для применения изменений!"
	L.confirm 	="Подтвердить"
	L.cancel 	="Отмена"
	L.setup	= "Настройка"
	L.ritss	= "Сбросить интерфейс для сохранения настроек"

	-- Настройки CVar
	L.comlc = "Отключить настройки во время боя"
	L.decpt = "Обнаружен плагин сбора ошибок, отключение стандартного отображения ошибок LUA"
	L.nedtc = "Ошибок не обнаружено. Плагин сбора включает стандартное отображение ошибок LUA"
	L.on 	="ВКЛ"
	L.off 	="ВЫКЛ"
	L.tgcb 	= "Полоса заклинаний цели"
	L.comif = "Информация о бое"
	L.teaml = "Расположение команды"
	L.tprl 	= "Расположение рейда на 20 человек"
	L.tfprl = "Расположение рейда на 25 человек"
	L.fprl 	= "Расположение рейда на 40 человек"
	L.tips	= "Подсказки"
	L.itine = "Если есть ошибка, перезагрузите интерфейс!"
	L.reload 	="Перезагрузить интерфейс?"
	L.confirm 	="Подтвердить"
	L.cancel 	="Отмена"
	L.uhset 	= "Настройки привычек использования"
	L.care 		="Осторожно!"
	L.comlc ="Полоса заклинаний цели"
	L.comlc ="Исходная информация о бое"

	-- Подсказки
	L.afk	= "АФК"
	L.offl	= "Не в сети"
	L.rare	= "Редкий"
	L.raree	= "Редкий элитный"
	L.elite	= "Элитный"
	L.ghost	= "Призрак"
	L.dead	= "Мертв"
	L.targ= "Цель"
	L.you	= "ВЫ"
	L.epicra	= "Эпический рейтинг"
	L.dungeons	= "Подземелья"
	L.ratle	= "Уровни рейтинга"
	L.item	= "Предмет"
	L.spell	= "Заклинание"

elseif (GetLocale() == "frFR") then
	L.resd	= "Rechargez l'interface pour rétablir les paramètres par défaut"
	L.confirm	= "Confirmer"
	L.cancel	= "Annuler"
	L.dtools2	= "Amélioration de l'interface"
	L.captext	= "|cff00EE00Shift|r - Maintenir pour déplacer les avatars standards, cellules de sang, infos, etc.\n(Régler la barre d'action peut la désactiver)\n|cff00EE00/di|r - Ouvre rapidement l'interface de configuration\n|cff00EE00/npd|r - Restaure les paramètres par défaut des barres de vie"
	L.printh2	= "|cff00EE00/rl|r - Recharge l'interface\n|cff00EE00/di|r - Ouvre rapidement l'interface de configuration"
	L.printh	= "Instructions"

	L.acu1	= "Barre d'action"
	L.acu2	= "Amélioration et décoration de la barre d'action"
	L.acc1	= "Bordure noire"
	L.acc2	= "Colorer la bordure des boutons d'action"
	L.acp1	= "Décoration avancée"
	L.acp2	= "Décorer le fond des boutons d'action"
	L.acr1	= "Cacher l'animation des icônes"
	L.acr2	= "Désactiver l'animation de lancement sur les nouvelles icônes (10.0)"
	L.unu1	= "Amélioration des cadres"
	L.unu2	= "Améliorer et décorer les cadres d'unités par défaut"
	L.unft1 = "Texture Élite"
	L.unft2 = "Cadre joueur avec texture de dragon doré"
	L.una1 	= "Disparition du cadre joueur"
	L.una2	= "Faire disparaître le cadre si aucune cible pendant le combat"
	L.pnc1	= "Renommer le personnage"
	L.pnc2	= "|cff00FF00/gn/name|r - Modifier le nom du personnage local"
	L.unfn1 = "Cacher le nom"
	L.unfn2 = "Cacher le nom du joueur"
	L.unc1	= "Couleurs de classe"
	L.unc2	= "Utiliser des couleurs de classe plus vives"
	L.otb1	= "Décoration du suivi"
	L.otb2	= "Décorer le texte de suivi des quêtes (peut buguer en combat)"
	L.sfu1	= "Décoration des polices"
	L.sfu2	= "Décorer la majorité des textes du jeu"
	L.ruu1	= "Décoration du cadre raid"
	L.ruu2	= "Améliorer les cadres raid"
	L.npu1	= "Amélioration des barres de vie"
	L.npu2	= "Décoration simple des barres de vie"
	L.tiu1	= "Amélioration des infobulles"
	L.tiu2	= "Décorer et améliorer les infobulles souris"

	L.aur1	= "Réparation auto"
	L.aur2	= "Réparer automatiquement l’équipement (priorité à la guilde)"
	L.aus1	= "Vente auto"
	L.aus2	= "Vente automatique des objets gris"
	L.aua1	= "Capture auto"
	L.aua2	= "Capture automatique lors des hauts faits"
	L.aug1	= "Formation auto"
	L.aug2	= "Formation automatique des textes chiffrés (|cffFFFF00/1|r)"
	L.fsl1	= "Loot rapide"
	L.fsl2	= "Accélérer la fenêtre de loot"
	L.ist1	= "Alerte interruption"
	L.ist2	= "Avertir quand une incantation est interrompue"
	L.vap1	= "Annonces vocales"
	L.vap2	= "Annonce vocale lors d'un gain de marque"
	L.bfm1	= "Déplacement des panneaux"
	L.bfm2	= "Déplacement libre des panneaux intégrés"
	L.ifs1	= "Infos système"
	L.ifs2	= "Vitesse de déplacement, FPS, Latence, Mémoire"
	L.ifsb1	= "Police grande taille"
	L.ifsb2	= "Agrandir la police des infos système"
	L.cfp1	= "Amélioration du chat"
	L.cfp2	= "Améliorer et décorer la fenêtre de chat"
	L.cfbb1	= "Bouton en bas"
	L.cfbb2	= "Déplacer le bouton du chat en bas de la fenêtre"
	L.cbi1	= "Indicateur de combat"
	L.cbi2	= "Indicateur de combat de Bigfoot"

	L.oufd1	= "Orbe Diablo"
	L.oufd2	= "Cadre joueur façon Diablo par oUF"
	L.oufcc1= "Couleur de classe"
	L.oufcc2= "Colorer l’orbe selon la classe"
	L.dpet1	= "Cadre familier"
	L.dpet2	= "Cadre du familier au-dessus de l’orbe de vie"
	L.dduf1	= "Cadre par défaut"
	L.dduf2	= "Activer le cadre joueur par défaut (caché par oUF)"
	L.uisl1	= "Verrouillage échelle UI"
	L.uisl2	= "Verrouille l’échelle de l’interface (nécessite de repositionner ensuite)"
	L.daml1	= "Réglage fin des actions"
	L.daml2	= "Personnaliser et verrouiller certaines barres d’actions (peut buguer en combat)"

	L.tipc1	= "Astuce : Suivre"
	L.tipc2	= "Astuce : Ne pas suivre"
	L.tipc3	= "Astuce : Suivre hors combat"
	L.sqw1	= "Délai d’incantation"
	L.sqw2	= "Délai entre les sorts"
	L.brtx	= "Version"
	L.adrl	= "Recharger"
	L.liver	= "En direct"
	L.slb	= "Recommandé"
	L.resdef	= "Réinitialiser par défaut"
	L.respos	= "Réinitialiser la position"
	L.liveroom	= "|cffEEFF7FDouyuLive :|r427397"
	L.print	= "Ouvrir l’interface de configuration"

		-- Chat
	L.say		= "S"
	L.yell		= "Y"
	L.party		= "P"
	L.guild		= "G"
	L.raid		= "R"
	L.instance	= "I"
	L.general1	= "G"
	L.general2	= "Général"
	L.general3	= "Vous n'avez pas de canal général"
	L.trade1	= "T"
	L.trade2	= "Commerce"
	L.trade3	= "Vous n'êtes pas dans le canal Commerce, rejoignez-le en capitale"
	L.lookingforgroup1	= "L"
	L.lookingforgroup2	= "RechercheGroupe"
	L.lookingforgroup3	= "Rejoint le canal RechercheGroupe"
	L.lookingforgroup4	= "Quitte le canal RechercheGroupe"
	L.world1	= "W"
	L.world2	= "Monde"
	L.world3	= "Rejoint le canal Monde"
	L.world4	= "Quitte le canal Monde"
	L.rep		= "R"
	L.eql		= "Niv. Éq."
	L.class		= "Classe"
	L.spec		= "Spé"

	-- Info
	L.fps 		= "FPS"
	L.lag 		= "Latence"
	L.player 	= "P"
	L.target 	= "T"
	L.vehicle 	= "V"
	L.none 		= "Aucun"
	L.lootspec 	= "SPÉC"
	L.str 		= "Str"
	L.agi 		= "Agi"
	L.int 		= "Int"
	L.cri 		= "Cri"
	L.has 		= "Has"
	L.mas 		= "Mas"
	L.ver 		= "Ver"
	L.clearm	= "Nettoyer la mémoire"
	L.total		= "Total"
	L.totalb	= "Total (incl. Blizzard)"
	L.sspec		= "Changer de spé"
	L.nospec	= "Pas encore spécialisé"
	L.slspec	= "Changer spé de butin"

	-- Modules
	L.guildrepair	= "Réparation via la guilde effectuée"
	L.guildra		= "Réparations de guilde restantes"
	L.selfrepair	= "Réparation à vos frais"
	L.norepair		= "Vous n'avez pas assez d'argent pour réparer l'équipement."
	L.sellg			= "Vente d'objets gris"
	L.hidoroff		= "Joueur invisible ou hors ligne, invitation impossible"
	L.cutin 		= "Couper "
	L.enytc 		= "Entrez le nom à modifier, laissez vide pour restaurer"
	L.carti 		= "Confirmer et recharger l'interface"

	-- Autres
	L.buyco		= "Achat d’un objet réussi"
	L.buydpc	= "Échec de l'achat, prix modifié"
	L.buyalp	= "Acheter au prix le plus bas"
	L.untre		= "Impossible de réinitialiser"
	L.hbre		= "Réinitialisé"
	L.ltteam	= "Quitter l'équipe"
	L.ftayt		= "Votre groupe est complet et sera retiré de la liste"
	L.era		= "ÈRE"

	-- Configuration de l'addon
	L.cdscr		= "Paramètres modifiés pour DBM, Skada... Recharge requise !"
	L.confirm 	= "Confirmer"
	L.cancel 	= "Annuler"
	L.setup		= "Configurer"
	L.ritss		= "Réinitialiser l'interface pour sauvegarder les paramètres"

	-- CVars
	L.comlc 	= "Désactiver les paramètres en combat"
	L.decpt 	= "Plugin de collecte d'erreurs détecté, affichage des erreurs LUA désactivé"
	L.nedtc 	= "Aucune erreur détectée. Plugin actif pour afficher les erreurs LUA"
	L.on 		= "ON"
	L.off 		= "OFF"
	L.tgcb 		= "Barre d'incantation cible"
	L.comif 	= "Infos de combat"
	L.teaml 	= "Disposition du groupe"
	L.tprl 		= "Disposition raid 20"
	L.tfprl 	= "Disposition raid 25"
	L.fprl 		= "Disposition raid 40"
	L.tips		= "Astuces"
	L.itine 	= "En cas d’erreur, rechargez l’interface !"
	L.reload 	= "Recharger l'interface ?"
	L.confirm 	= "Confirmer"
	L.cancel 	= "Annuler"
	L.uhset 	= "Préférences d'utilisation"
	L.care 		= "Attention !"

	-- Infobulles
	L.afk		= "AFK"
	L.offl		= "Hors ligne"
	L.rare		= "Rare"
	L.raree		= "Rare élite"
	L.elite		= "Élite"
	L.ghost		= "Fantôme"
	L.dead		= "Mort"
	L.targ		= "Cible"
	L.you		= "VOUS"
	L.epicra	= "Score épique"
	L.dungeons	= "Donjons"
	L.ratle		= "Niveaux de cote"
	L.item		= "Objet"
	L.spell		= "Sort"



else
	
	L.resd	= "Reload interface to restore default"
	L.confirm	= "Confirm"
	L.cancel	= "Cancel"
	L.dtools2	= "UI beautify"
	L.captext	= "|cff00EE00Shift|r down to move default avatars, dark blood cells, data information, etc\n(Adjusting the action bar can turn off the action bar)\n|cff00EE00/di|r Quickly open the settings interface\n|cff00EE00/npd|r Restore nameplates default settings"
	L.printh2	= "|cff00EE00/rl|r Reload interface\n|cff00EE00/di|r Quickly open the settings interface"
	L.printh	= "Instructions"

	L.acu1	= "ActionBar"
	L.acu2	= "Action bar enhance and beautify"
	L.acc1	= "Blackout border"
	L.acc2	= "Dye action bar button border"
	L.acp1	= "Advanced beautify"
	L.acp2	= "Beautify the background of the action bar button border"
	L.acr1	= "Hide icon animation"
	L.acr2	= "Close the newly added icon casting animation in 10.0"
	L.unu1	= "Frame enhance"
	L.unu2	= "Default unitframe beautify enhance"
	L.unft1 = "Elite texture"
	L.unft2 = "Player frame made of golden dragon texture"
	L.una1 	= "PlayerFrame fadeout"
	L.una2	= "A framework for gradually disappearing avatars without a target in battle"
	L.pnc1	= "Character renaming"
	L.pnc2	= "|cff00FF00/gn/name|r Change local player character names"
	L.unfn1 = "Hide name"
	L.unfn2 = "Hide player name"
	L.unc1	= "Class color adjustment"
	L.unc2	= "Use a bright set of professional colors"
	L.otb1	= "Tracking beautify"
	L.otb2	= "Task tracking text beautification(Possible interface behavior failure during combat)"
	L.sfu1	= "Font beautify"
	L.sfu2	= "Beautify most of the text in the game"
	L.ruu1	= "RaidFrame beautify"
	L.ruu2	= "RaidFrame beautify"
	L.npu1	= "Nameplate enhance"
	L.npu2	= "Simple Nameplate beautify enhance"
	L.tiu1	= "Tip enhance"
	L.tiu2	= "Mouse tip beautify and enhance"

	L.aur1	= "Auto repair"
	L.aur2	= "Auto repair equipment (priority given to guild repairs)"
	L.aus1	= "Auto sales"
	L.aus2	= "Autoally sell gray garbage"
	L.aua1	= "Auto screenshot"
	L.aua2	= "Obtain Auto screenshots of achievements"
	L.aug1	= "Auto formation"
	L.aug2	= "Auto formation of ciphertext(|cffFFFF00/1|r)"
	L.fsl1	= "Quick Pick"
	L.fsl2	= "Pick frame acceleration"
	L.ist1	= "Interrupt prompt"
	L.ist2	= "Interrupt target casting prompt"
	L.vap1	= "Voice Announcements"
	L.vap2	= "Mark gain voice prompt"
	L.bfm1	= "Panel movement"
	L.bfm2	= "Free movement of builtin panel frame"
	L.ifs1	= "Data information"
	L.ifs2	= "Movement speed, FPS, Lag, Memory"
	L.ifsb1	= "Large font"
	L.ifsb2	= "Increase the font size of data information"
	L.cfp1	= "Chat enhance"
	L.cfp2	= "Talk about beautify and enhance"
	L.cfbb1	= "Bottom button"
	L.cfbb2	= "Move the chat bar button to the bottom of the frame"
	L.cbi1	= "CombatIndicator"
	L.cbi2	= "CombatIndicator by Bigfoot"

	L.oufd1	= "Diablo Orb"
	L.oufd2	= "Diablo Orb PlayerFrame by oUF"
	L.oufcc1= "Class color"
	L.oufcc2= "Orb dyeing of class color"
	L.dpet1	= "Pet frame"
	L.dpet2	= "Pet frame above the orb of life"
	L.dduf1	= "Default Frame"
	L.dduf2	= "Enable default playerFrame hidden by oUF"
	L.uisl1	= "UI Scale lock"
	L.uisl2	= "Open and lock UI scale(After adjusting the UI scale, it is necessary to reset the position)"
	L.daml1	= "Actionfine-tuning"
	L.daml2	= "Customize and lock some action bars(Editing mode will report errors during combat)"

	L.tipc1	= "Tip: Follow"
	L.tipc2	= "Tip: Do not follow"
	L.tipc3	= "Tip: Non Combat Follow"
	L.sqw1	= "Cast delay"
	L.sqw2	= "Cast sequence delay"
	L.brtx	= "Version"
	L.adrl	= "Reload"
	L.liver	= "LiveRoom"
	L.slb		= "Recommendation"
	L.resdef	= "Restore default"
	L.respos	= "Reset position"
	L.liveroom	= "|cffEEFF7FDouyuLive:|r427397"
	L.print	= "Open the settings interface"


	--chat
	L.say		= "S"
	L.yell		= "Y"
	L.party		= "P"
	L.guild		= "G"
	L.raid		= "R"
	L.instance		= "I"
	L.general1		= "G"
	L.general2		= "General"
	L.general3		= "You don't have a general channel"
	L.trade1		= "T"
	L.trade2		= "Trade"
	L.trade3		= "You are not on the trading channel, please join in the main city"
	L.lookingforgroup1		= "L"
	L.lookingforgroup2		= "LookingForGroup"
	L.lookingforgroup3		= "Joined LookingForGroup"
	L.lookingforgroup4		= "Leaving LookingForGroup"
	L.world1		= "W"
	L.world2		= "world"
	L.world3		= "Joined World Channel"
	L.world4		= "Leaving World Channel"
	L.rep		= "R"
	L.eql		= "Eq level"
	L.class		= "Class"
	L.spec		= "Spec"


	--info
	L.fps 	= "FPS"
	L.lag 	= "Lag"
	L.player 	= "P"
	L.target 	= "T"
	L.vehicle 	= "V"
	L.none 	= "Nil"
	L.lootspec 	= "SPEC"
	L.str 	= "Str"
	L.agi 	= "Agi"
	L.int 	= "Int"
	L.cri 	= "Cri"
	L.has 	= "Has"
	L.mas 	= "Mas"
	L.ver 	= "Ver"
	L.clearm	= "Clean up memory"
	L.total		= "Total"
	L.totalb	= "Total incl.Blizzard"
	L.sspec		= "Switch Spec"
	L.nospec	= "Not specialized yet"
	L.slspec	= "Switch Pick Spec"


	--modules
	L.guildrepair	= "This time using guild repair"
	L.guildra		= "Remaining guild repairs available"
	L.selfrepair	= "Self funded repair"
	L.norepair		= "I don't have money to repair equipment."
	L.sellg			= "Selling garbage"
	L.hidoroff		= "The other party is invisible or has no character online, unable to invite"
	L.cutin 		= "Cut "
	L.enytc 		= "Enter the name you want to change, do not enter to restore the original name"
	L.carti 		= "Confirm and reload the interface"
	
	
	--other
	L.buyco		= "Successfully purchased 1 item"
	L.buydpc	= "Purchase failure, price change"
	L.buyalp	= "Buy one at the lowest price"
	L.untre		= "Unable to reset"
	L.hbre		= "Has been reset"
	L.hbre		= "Has been reset"
	L.ltteam	= "Leaving the team"
	L.ftayt		= "For this activity, your team is full and will be removed from the list"
	L.era		= "ERA"
	
	
	--setaddon
	L.cdscr	= "DBM, Skada.. Settings have been changed, reloading interface application changes!"
	L.confirm 	="Confirm"
	L.cancel 	="Cancel"
	L.setup	= "Set up"
	L.ritss	= "Reset interface to save settings"


	--setcvar
	L.comlc = "Disable settings during battles"
	L.decpt = "Detected error collection plugin turning off default LUA error display"
	L.nedtc = "No error detected. The collection plugin opens the default LUA error display"
	L.on 	="ON"
	L.off 	="OFF"
	L.tgcb 	= "Target casting bar"
	L.comif = "Combat information"
	L.teaml = "Team Layout"
	L.tprl 	= "20 person raid layout"
	L.tfprl = "25 person raid layout"
	L.fprl 	= "40 person raid layout"
	L.tips	= "Tips" 
	L.itine = "If there is an error, please reload the interface!"
	L.reload 	="Reload UI?"
	L.confirm 	="Confirm"
	L.cancel 	="Cancel"
	L.uhset 	= "Usage habits settings"
	L.care 		="Careful!"
	L.comlc ="Target casting bar"
	L.comlc ="Original Combat information"


	--tooltip
	L.afk	= "AFK"
	L.offl	= "Offline"
	L.rare	= "Rare"
	L.raree	= "Rareelite"
	L.elite	= "Elite"
	L.ghost	= "Ghost"
	L.dead	= "Dead"
	L.targ= "Target"
	L.you	= "YOU"
	L.epicra	= "Epic Rating"
	L.dungeons	= "Dungeons"
	L.ratle	= "Rating Levels"
	L.item	= "Item"
	L.spell	= "Spell"
	
end